services:
  db:
    image: mysql:8.3.0
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=store
    volumes:
      - ./tearup/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 5s
      retries: 10
      start_period: 5s

  liquibase:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: liquibase
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./database:/liquibase/changelog
    environment:
      - LIQUIBASE_COMMAND_URL=jdbc:mysql://db:3306/store?useSSL=false&allowPublicKeyRetrieval=true
      - LIQUIBASE_COMMAND_USERNAME=user
      - LIQUIBASE_COMMAND_PASSWORD=password
      - LIQUIBASE_COMMAND_CHANGELOG_FILE=changelog-master.xml

  admin:
    image: adminer
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
